name: Github Pages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - name: Setup toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: ./trunk build --release --public-url $public_url
        env:
          public_url: "https://nihilityer.top/${{ github.event.repository.name }}"
      - name: Update sw.js with hashed filename
        run: |
          generated_file=$(ls dist/easy_protobuf_edit-*.js)
          if [ -z "$generated_file" ]; then exit 1; fi
          filename=$(basename "$generated_file")
          hash_part="${filename#easy_protobuf_edit-}"
          hash_part="${hash_part%.js}"
          sed -i "5s|.*|'./easy_protobuf_edit-${hash_part}.js',|" ./dist/sw.js
          sed -i "6s|.*|'./easy_protobuf_edit-${hash_part}_bg.wasm',|" ./dist/sw.js
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
