name: Release Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ inputs.version || steps.tag.outputs.tag }}
  build:
    needs: get-version
    strategy:
      matrix:
        include:
          # Linux targets
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""

          # Windows targets
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: ".exe"

          # macOS targets
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            ext: ""

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mkdir release
          BIN_PATH="./target/${{ matrix.target }}/release/easy_protobuf_edit${{ matrix.ext }}"
          RELEASE_NAME="easy_protobuf_edit-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.ext }}"
          cp "$BIN_PATH" "release/$RELEASE_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: epe-${{ env.VERSION }}-${{ matrix.target }}
          path: release/

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: epe-${{ env.VERSION }}-*
          merge-multiple: true
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
