name: Release Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux targets
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""

          # Windows targets
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: ".exe"

          # macOS targets
          - target: aarch64-apple-darwin
            os: macos-latest
            ext: ""

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mkdir release
          cp "./target/${{ matrix.target }}/release/easy_protobuf_edit${{ matrix.ext }}" "release/easy_protobuf_edit-${{ inputs.version || github.ref }}-${{ matrix.target }}${{ matrix.ext }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: epe-${{ inputs.version || github.ref }}-${{ matrix.target }}
          path: release/

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: epe-${{ inputs.version || github.ref }}-*
          merge-multiple: true
          path: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
